### ISSUE TITLE
The current batch processing design is bad

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#3]
The current batch processing design is bad, because : 

- [x]  ~~`AddressReader#open()`~~ `BatchItemReader#open()` does logical treatment. Normally, this method supposes to be used only for a simple opening operation, e.g load entities using session. In current implementation, it is used to construct `AddLuceneWork`. This method loads all entities at one time. So that means if there're an 1PB database, it will load 1PB data all together ? That's not reasonable. :point_right: Issue #5 
- [x]  ~~`AddressProcessor`~~ `BatchItemProcessor` does less things than expected : many stuffs are done in ~~`AddressReader`~~ `BatchItemReader`. (not sure ⚠️ ) For instance, the reader only loads IDs from `IndexingContext` and that's OK 
- [x] Not sure the `Executor` is well handled. Exception handling is another topic to do. It shouldn't be included in the batch architecture design. 
- [x]  ~~`AddressWriter`~~ `BatchItemWriter` does nothing but to print the processed-entity in console. This has already been fixed in commit 9b8faa8. `BatchWriter` executes the given lists of `LuceneWork` now. 
- [x]  `#checkpointInfo()` are not used 👉  Issue #40
- [x]  `LinkedList` vs `ArrayList` vs `Queue` vs `Set` ? :point_right: Issue #8 . We use `Array` at the end.

**Comment by mincong-h** [comment]
## Modifications

### BatchItemProcessor

For the point §2, the processor runs a JPA query to obtain entities using an array of IDs.

**Comment by mincong-h** [comment]
done.
