### ISSUE TITLE
Dynamic flow configuration in job XML

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#33]
Can I configure dynamically the number of flows in job XML ? The current context is that there're N root entity types which need to be indexed. For these N types, I want to have N flows that runs in parallel. These flow have exactly the same execution logic.

> Why I don't what to use N partitions inside the same step ?

N entity types requires N partitions, that's one partition per entity type. But I don't want to use only one partition for one entity type. That will be too slow for certain. I want to give M partitions the a given entity type, where the number M will be configured dynamically.

Here's an example, I've 3 type of entities to be indexed : 

*  `Address`, 12000K records
*  `Stock`, 10K records
*  `Animal`, 1K records

If there's one partition per type, then there will be 3 partitions. Obviously, the partition of  `Address` will be the slowest.

This is a sub-task of #16 Use generic type in batch job.

**Comment by mincong-h** [comment]
In the page 40 of _JSR-352-1.0-Final-Release.pdf_, a flow is defined as below : 

> A flow defines a sequence of execution elements that execute together as a unit. When the flow is finished, it is the entire flow that transitions to the next execution element. A flow may transition to a step, split, decision, or another flow. A flow may contain step, flow, decision, and split execution elements. See section 8.5 for more on decisions. See section 8.4 for more on splits. The execution elements within a flow may only transition among themselves; they may not transition to elements outside of the flow. A flow may also contain the transition elements next, stop, fail, and end. See section 8.6 for more on transition elements.

> Syntax:
> ```xml
<flow id="{name}"next="{flow-id|step-id|split-id|decision-id}">
  <step> ... </step>
  ...
</flow>
```

**Comment by mincong-h** [comment]
Since every thing should be described explicitly inside the `<flow>` tag, I don't think defining flow dynamically is possible.

**Comment by mincong-h** [comment]
> So, what about index all entity types in the same step, using a appreciated partition plan ?

**Comment by mincong-h** [comment]
## TODO

- [ ] Create the `idQueues` in IndexingContext
- [ ] Provide a doable solution to identity the ID type of each entity
- [ ] Poll IDs from `idQueues` by choosing the target entity
- [ ] Compute the row number produced by `IdProducerBatchlet`
- [ ] Compute the number of partitions needed for the chunk

**Comment by mincong-h** [comment]
## Resume

The issue aimed to provide an reasonable partition plan for batch job _mass-index_. When we look back from the first comment, the workflow was : 

1.  The 1st idea : define dynamic workflow according to the entity entries. But I soon found out that it's impossible because the number of flows cannot be set dynamically.
2.  The 2nd idea : define partition plan according to the partition capacity. The job distributes different number of partitions to each entity, based on the their quantity. Then each partition is a consumer of the concurrent ID queue. IDs will be used to obtain the associated entities using JPA criteria with _IN_ condition.
3.  The 3rd idea : maintain the partition plan as described in the 2nd idea, without using the ID queue. The ID queue mechanism is now replaced by the scrollable results. You can find this refactoring in issue #97 Redesign the chunk in the job "mass-index".

I wrote this resume because this issue is really incomprehensible 💦 . Since everything is done, I'll close it now.
