### ISSUE TITLE
Prepare a tag for running the first version

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/gsoc-hsearch#41]
My mentor @gunnarmorling might need to run this project tonight or tomorrow. So I'll prepare the first tag _0.1_ for the project. The below tasks will be included : 

- [x] #28 Provide a README
- [x] #35 Rename "us-address" to "hsearch-jsr352" or similar
- [x] #36 Move "WebContents" to src/main/webapp
- [x] #14 Fix maven pom.xml
- [x] Clean up the code and provide more comprehensive logics, variables naming ...
- [x] Upload CSV file for different tables
- [x] Provide CSV importation scripts

And more tasks might be added later if I remember them.

The idea is the keep tags on master to track progress and provides runnable and stable code. Then, I'll use another branch for the development.

**Comment by mincong-h** [comment]
- [ ] Remove `./jse-chunk`
- [ ] Remove `./zoo-jpa`
- [ ] Move content of folder `./jsr352` to the root folder `./`

**Comment by mincong-h** [comment]
Pre-release 0.1 done.
